export { strict as b59 } from './vocabularies/b59.js'
export { strict as code } from './vocabularies/code.js'
export { strict as cube } from './vocabularies/cube.js'
export { strict as meta } from './vocabularies/meta.js'
export { strict as pipeline } from './vocabularies/pipeline.js'
export { strict as relation } from './vocabularies/relation.js'
